name: Pull Request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
        group: ${{ github.head_ref }}-pull-request
        cancel-in-progress: true

    strategy:
      matrix:
        node: [16, 18, 19]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
