name: Pull Request
on: pull_request
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Grab node version
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install deps
        uses: npm ci
      - name: Lint
        run: npm run lint:check
  
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Grab node version
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install deps
        uses: npm ci
      - name: Lint
        run: npm run format:check

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [16, 18, 19]
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4
  #     - name: Setup node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}
  #     - name: Install dependencies
  #       uses: bahmutov/npm-install@v1
  #       with:
  #         useLockFile: false
