name: Pull Request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ matrix.node }}-${{ github.head_ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        node: [16, 18, 19]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
