name: Release to npm registry
on: workflow_dispatch

permissions:
  contents: read # for checkout

jobs:
  release:
    name: 📦 Release package
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release
      cancel-in-progress: true
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Node.js version from .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Run semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
